### PR TITLE
first test of pg to mbx conversion

### PR DESCRIPTION
**Pull request by davidfarmer**
The directory
pgconverted
contains mbx versions of the pg files in
PCC/BasicAlgebra/AbsoluteValue

The file
pgconverted/absoluteValueEquation20.mbx
contains an error, because the variable in the input field does not fit a pattern I know.

I am not aware of other errors, but I was not sure how to do testing.

I think it is okay to accept this pull request, because all the changes are new files
in one new directory, and so can be deleted later.

Once things are working, I can put the conversions into whatever directory you specify.

All feedback/corrections/improvements welcome, of course.

### CODE REVIEW

**Comment by davidfarmer** [comment]
I have not yet converted all the ampersands and lesses.  I know what to do, but it
is slightly complicated because of how the different environments can nest within each other.

**Comment by Alex-Jordan** [comment]
The one problem that has the error is a special case. It is using a special answer checking mechanism written into one of the loaded macros. The problem is that right now, something like this is not provisioned for with the XSL. The _real_ problem is that it is a poorly written macro library that should have been written to make the problem code resemble normal problem code. I'll have to think about this.

I'd rather wait to accept PRs because I don't necessarily know that I want to increase the size of the repo's history with all of this. I can just make a branch and pull from your fork to test things. Making the PR gives me a very convenient way to know where to pull from though.

For checking how the output behaves, what we need is a single .mbx file that uses all the output. Then I can process that in various ways where the webwork server will tell me if anything is actually broken. (Checking when things are just unfaithfully converted but still functioning will be harder, but perhaps still doable using a diff utility.) Would it be easier for you to:

1. Add a single .mbx file to this that used include on all of the .mbx files?
2. Add a single .mbx file that literally included all of this output?

Some minor indentation niceties:

- Could `macro-file`s be indented within `pg-macros`?
- Could p/ul/li/p indentation be nested with indentation at each level?
- PG statement code is sensitive to extra whitespace. Stuff like:
```
<p>
            Enter multiple answers separated by commas, such as <m>x=1,x=-1</m>
          </p>
```
will matter if the whitespace scrubbing is not yet implemented for `mathbook-webwork-pg.xsl`. It would help with initial testing if we either get that scrubbing in place, or for now make the output just like:
```
<p>Enter multiple answers separated by commas, such as <m>x=1,x=-1</m></p>
```

**Comment by davidfarmer** [comment]
1. Add a single .mbx file to this that used include on all of the .mbx files?
    2. Add a single .mbx file that literally included all of this output?

You choose, and then tell me what markup goes at the top and bottom of the
file, and what goes around each WW problem.  (I have a slight preference
for 1., but very slight.)

I'll make some improvements to the indentation.

**Comment by davidfarmer** [comment]
I'll close this pull request and come back with one that makes testing easier and
fixes some of the known issues.  No need to reply to previous questions, and I'll direct
new questions to the ORCCA list.

Could take a few days.

**Comment by Alex-Jordan** [comment]
@davidfarmer I'd like to readjust course on how we proceed. It may take significantly more effort to convert the bulk of these libraries than what we actually need. Unless you think differently, I'd like to start going through one section of ORCCA at a time, and getting the conversions right there. Then from section to section, there is hopefully less and less to fuss about. 

With each section, Carl or I would actually paste the conversion into ORCCA source at some level. If the problems behave for that section, great. If not, we provide specifics on how to improve the translation.

If this seems like a better approach to you, then below are the files used in the first section of the book. Looking at the first file on the list, the new things I see not covered by earlier work are:

- `##Multiplication Facts`
This would become an h2 header. So I don't know what good MBX would be. Do you have any ideas?
- There are things like
[\`\` [@$num1[0]@] \cdot [@$num2[0]@] \`\`]
which I think should become
`<me> <var name="$num1[0]" /> \cdot <var name="$num2[0]" /></me>`
- The solution has:
```
    [``
\begin{aligned}[t]
   [@$num1[0]@] \cdot [@$num2[0]@] &= [@$products[0]@] \\
   ...
   [@$num1[9]@] \cdot [@$num2[9]@] &= [@$products[9]@]
\end{aligned}
``]
```
which should become:
```
<p><md>
  <mrow><var name="$num1[0]" /> \cdot <var name="$num2[0]" /> \amp= <var name="$products[0]" /></mrow>
  ...
  <mrow><var name="$num1[9]" /> \cdot <var name="$num2[9]" /> \amp= <var name="$products[9]" /></mrow>
</md></p>
```


BasicMath/MultiplicationDivision/multiplicationTable10.pg
BasicMath/MultiplicationDivision/multiplicationTable15.pg
BasicMath/MultiplicationDivision/multiplicationTable20.pg
BasicMath/MultiplicationDivision/multiplicationTable25.pg
BasicMath/AdditionSubtraction/Addition10.pg
BasicMath/AdditionSubtraction/Addition20.pg
BasicMath/AdditionSubtraction/Subtraction10.pg
BasicMath/AdditionSubtraction/Subtraction20.pg
BasicMath/Decimal/AddSubtractDecimals10.pg
BasicMath/Decimal/AddSubtractDecimals12.pg
BasicMath/Decimal/AddSubtractDecimals20.pg
BasicMath/Decimal/AddSubtractDecimals30.pg
BasicMath/Decimal/AddSubtractDecimals40.pg
BasicMath/Decimal/MultiplyDivideDecimals10.pg
BasicMath/Decimal/MultiplyDivideDecimals20.pg
BasicMath/Decimal/MultiplyDivideDecimals30.pg
BasicMath/Decimal/MultiplyDivideDecimals40.pg
BasicMath/Decimal/MultiplyDivideDecimals50.pg
BasicMath/Decimal/MultiplyDivideDecimals60.pg
BasicMath/Decimal/MultiplyDivideDecimals70.pg
BasicMath/Decimal/MultiplyDivideDecimals80.pg
BasicMath/Decimal/MultiplyDivideDecimals90.pg
BasicMath/Decimal/MultiplyDivideDecimals100.pg
BasicMath/Decimal/MultiplyDivideDecimals110.pg
BasicMath/Decimal/MultiplyDivideDecimals120.pg
BasicMath/Decimal/MultiplyDivideDecimals130.pg
BasicMath/Decimal/MultiplyDivideDecimals140.pg
BasicMath/Decimal/MultiplyDivideDecimals150.pg
BasicMath/Decimal/MultiplyDivideDecimals160.pg
BasicMath/Decimal/MultiplyDivideDecimals170.pg
BasicMath/Decimal/MultiplyDivideDecimals180.pg
BasicMath/Decimal/MultiplyDivideDecimals190.pg
BasicMath/Decimal/MultiplyDivideDecimals200.pg
BasicMath/Decimal/MultiplyDivideDecimals210.pg
BasicMath/Decimal/MultiplyDivideDecimals220.pg
BasicMath/Decimal/MultiplyDivideDecimals230.pg
BasicMath/Decimal/MultiplyDivideDecimals240.pg
BasicMath/Decimal/MultiplyDivideDecimals250.pg
BasicMath/Miscellaneous/ExponentDefinition05.pg
BasicMath/Miscellaneous/ExponentDefinition15.pg
BasicMath/MultiplicationDivision/DivideByZero10.pg
BasicMath/MultiplicationDivision/DivideTrailingZero10.pg
BasicMath/MultiplicationDivision/MultiplyTrailingZero10.pg
BasicMath/AdditionSubtraction/AdditionSubtractionApplications10.pg
BasicMath/AdditionSubtraction/AdditionSubtractionApplications20.pg
BasicMath/AdditionSubtraction/AdditionSubtractionApplications30.pg
BasicMath/AdditionSubtraction/AdditionSubtractionApplications40.pg
BasicMath/AdditionSubtraction/AdditionSubtractionApplications50.pg
BasicMath/AdditionSubtraction/AdditionSubtractionApplications60.pg
BasicMath/Decimal/DecimalAndMoney10.pg
BasicMath/Decimal/DecimalAndMoney10.pg
BasicMath/Miscellaneous/SquarePerimeterArea10.pg
BasicMath/MultiplicationDivision/DivisionWordProblem10.pg
BasicMath/MultiplicationDivision/DivisionWordProblem20.pg
BasicMath/MultiplicationDivision/DivisionWordProblem30.pg
BasicMath/MultiplicationDivision/DivisionWordProblem40.pg
BasicMath/MultiplicationDivision/DivisionWordProblem50.pg
BasicMath/MultiplicationDivision/DivisionWordProblem52.pg
BasicMath/MultiplicationDivision/DivisionWordProblem60.pg
BasicMath/MultiplicationDivision/DivisionWordProblem62.pg
BasicMath/MultiplicationDivision/DivisionWordProblem70.pg
BasicMath/MultiplicationDivision/DivisionWordProblem80.pg
BasicMath/MultiplicationDivision/DivisionWordProblem90.pg
BasicMath/MultiplicationDivision/DivisionWordProblem100.pg
BasicMath/MultiplicationDivision/DivisionWordProblem110.pg
BasicMath/MultiplicationDivision/MultiplicationWordProblem10.pg
BasicMath/MultiplicationDivision/MultiplicationWordProblem20.pg
BasicMath/MultiplicationDivision/MultiplicationWordProblem30.pg
BasicMath/MultiplicationDivision/MultiplicationWordProblem40.pg
BasicMath/MultiplicationDivision/MultiplicationWordProblem50.pg
BasicMath/MultiplicationDivision/MultiplicationWordProblem60.pg
BasicMath/MultiplicationDivision/MultiplicationWordProblem70.pg
BasicMath/MultiplicationDivision/MultiplicationWordProblem80.pg
BasicMath/MultiplicationDivision/MultiplicationWordProblem90.pg
BasicMath/MultiplicationDivision/RemainderWordProblem10.pg
BasicMath/MultiplicationDivision/RemainderWordProblem20.pg
BasicMath/MultiplicationDivision/RemainderWordProblem30.pg
BasicMath/MultiplicationDivision/RemainderWordProblem40.pg
BasicMath/MultiplicationDivision/RemainderWordProblem50.pg

**Comment by davidfarmer** [comment]
I think the only real change you are suggesting is to start working
on a different section, and not necessarily convert all the problems
initially.  No problem doing that.  I am still a couple days from being
able to get back to this.

**Comment by Alex-Jordan** [comment]
Yes, that's right. Changing what the way points would be for assessing the conversion.

**Pull request closed without merging**
